### ISSUE TITLE
Generating BAF files from scRNAseq

### ISSUE THREAD

**Issue by XYZ-NCI** [akdess/CaSpER#13] opened 2020-04-15 15:29 UTC
Hi! 

Thank you for the great tool! This is really helpful. I was wondering, to generate the BAF file, how do we do it for multiple scRNAseq result that I typically integrate in Seurat? Do you have a more detailed tutorial for this purpose? Thank you!

X

**Comment by akdess** [comment] 2020-04-23 02:57
Hi @XYZ-NCI, Thanks a lot for your comment. SOrry for the late reply.  For integrated seurat object you can use integrated@assays$RNA@count as the raw.data in CreateCasperObject, and use matrix.type="raw" in CreateCasperObject. Casper is now updated to include the raw count data. Hope it helps. We will definitely include a tutorial for the integrated data.

**Comment by XYZ-NCI** [comment] 2020-04-23 11:35
Hi Akdes,
Thank you so much for your kind reply. I wonder how would you run BAFextract to generate the maf.rda file you used in the 10x tutorial, if you are using integrated Seurat object.
Thanks a lot!

**Comment by akdess** [comment] 2020-04-24 04:44
Hi @XYZ-NCI, 

Thanks a lot for your input. We are working on extracting BAF signal for each cell in 10x data. You should be able to do that manually by cell barcodes, i.e. generating bam files for each cell and running BAFExtract, but I understand that it would be time consuming. 

You have two options. You can use the same maf file for all samples. Similar to the demo in https://github.com/akdess/CaSpER/blob/master/demo/MM135_10X.R
Or you can ignore BAF shift totally: 
after saying CreateCasperObject with parameters: loh.name.mapping=NULL and loh=NULL

Instead of runCasper you can run the following: 

final.objects <- list()
loh.list <- list()
cnv.list <- list()


message("Performing HMM segmentation...")

for (i in 1:object@cnv.scale) {
    cnv.list[[i]] <- PerformSegmentationWithHMM(object, cnv.scale = i, removeCentromere = F, cytoband = cytoband)
}

for (i in 1:3) {

	object <- cnv.list[[i]]
	object@segments$states2 <- rep("neut", length(object@segments$state))

	object@segments$states2[as.numeric(as.character(object@segments$state)) == 1] <- "del"
	object@segments$states2[as.numeric(as.character(object@segments$state)) == 5] <- "amp"
	final.objects[[i]] <- generateLargeScaleEvents(object)
}

**Comment by XYZ-NCI** [comment] 2020-04-28 16:47
Hi! Thank you for your reply. I have tried to merge bam files (multiple cells from each of the multiple patients with two control samples). Expression data of the same cells were merged in Seurat with the patient info (sample ID) annotated. I was able to run through the pipeline with a practice dataset (one sample + control samples). When assigning names to the loh object, how do you assign the proper sample name to the multiple cells that come from that sample?
Thanks!
XZ

**Comment by XYZ-NCI** [comment] 2020-04-28 17:55
I wonder if it’s feasible to run BAFExtract for each patient sample (with multiple cells) separately, load merged expression matrix and add the BAF information to the specific patient sample at the step of “CreateCasperObject”? I would like to use CASPER to perform analysis and generate similar plots as you showed in Figure5 of the Nature Communication paper. Basically generate BAF for each sample separately and merge at some point so the LOH information can be added to the side of expression for downstream analysis. Thanks!

**Comment by akdess** [comment] 2020-04-29 05:28
Hi @XYZ-NCI, 
For single cell GBM study in Figure 5, I merged the cells for each patient using the following commands: 
   bamtools merge -list <bam_file_names> -out <sample_name>_merged.bam 
   samtools index <sample_name>_merged.bam
And for each patient I ran BAFExtract. Hope it helps. It is in our to-do list to make it automatically for 10x data. 

Thanks a lot, 
Akdes

**Comment by XYZ-NCI** [comment] 2020-04-29 09:28
Hi Akdes,

Thank you for getting back.
I did the same thing of merging the bam files of each patient and running BAFExtract. Then I ran readBAFExtractOutput to read the BAF result for each sample and name each of them. My question is, at the step of “loh.name.mapping”, how do you match the BAF result of each patient to their merged expression matrix?

Thanks a lot!
XZ

**Comment by akdess** [comment] 2020-04-30 02:45
Hi @XYZ-NCI, 

You can have a look at loh.name.mapping data.frame in scell GBM demo rdata: https://github.com/akdess/CaSpER/blob/master/data/scell_gbm.rda 
Hope it helps.
Best,
Akdes

**Comment by XYZ-NCI** [comment] 2020-05-01 17:52
Hi Akdes,

Thank you for your reply. I downloaded the scell_gbm data and formatted my data in the save format. Everything should work as illustrated in your example, except that my data is much larger (I was able to run it through the pipeline using a smaller dataset). The raw object was created just fine (size = 19.2G) but it failed at the step of runCaSpER with a huge core file generated (size = 85.59G). I include the error message here for your reference. Do you know what might be the reason? I am using HPC with 2 core and 1200g memory.

*** caught segfault ***
address 0x30, cause 'memory not mapped'

Traceback:
1: aperm(output$xi, c(3, 2, 1))
2: is.data.frame(x)
3: colSums(aperm(output$xi, c(3, 2, 1)))
4: t(colSums(aperm(output$xi, c(3, 2, 1))))
5: manualSegment(correctOut$copy, chr, autosomes, param, maxiter,     verbose)
6: HMMsegment(correctOut = rdata, param = object@hmmparam, verbose = F)
7: PerformSegmentationWithHMM(object, cnv.scale = i, removeCentromere = T,     cytoband = cytoband)
8: runCaSpER(object, removeCentromere = T, cytoband = cytoband_hg38,     method = "iterative")
An irrecoverable exception occurred. R is aborting now ...
/var/spool/slurm/slurmd/job57220421/slurm_script: line 10: 141787 Segmentation fault      (core dumped) R --vanilla < PDX.R > PDX.R.out

Any insight would be very much appreciated!
Thank you!
Xiyuan

**Comment by akdess** [comment] 2020-06-12 03:06
Hi @XYZ-NCI , I am very sorry for the late reply, I missed your question. If you can send me your R object I can try to understand the issue, My email is akdess at gmail com 
Best, 
Akdes

**Comment by singlecoated** [comment] 2020-07-03 10:04
I was getting exactly the same error messages and found out I was giving the CreateCasperObject a wrong annotation data frame in incorrect format.

Just in case it throws some light.

Best.

**Comment by akdess** [comment] 2020-07-17 05:10
Thanks a lot @singlecoated!

**Closed as completed** 2020-10-09 20:40 UTC

**Comment by lifan18** [comment] 2022-08-08 06:49
I got the same error messages as `*** caught segfault ***
address 0x30, cause 'memory not mapped'
`.
I didn't figure out it was caused by the memory requirements or by R libraries installation. May this information give a clue for the next .

Best.
